Ajustes dockerfile para Prod

diff --git a/dockerfile.prod b/dockerfile.prod
--- a/dockerfile.prod
+++ b/dockerfile.prod
@@ -1,4 +1,4 @@
-FROM node:24.4.1-alpine3.21 AS base
+FROM node:22.14-alpine3.20 AS base
 
 FROM base AS deps
 RUN apk add --no-cache libc6-compat
@@ -6,9 +6,17 @@ WORKDIR /app
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
 
 RUN \
-  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
-  else echo "Lockfile not found." && exit 1; \
+  if [ -f yarn.lock ]; then \
+    yarn --frozen-lockfile; \
+  elif [ -f pnpm-lock.yaml ]; then \
+    corepack enable && \
+    corepack prepare pnpm@10.12.1 --activate && \
+    pnpm config set registry https://registry.npmjs.org/ && \
+    pnpm config set fetch-retries 10 && \
+    pnpm config set fetch-timeout 600000 && \
+    pnpm install --frozen-lockfile --ignore-scripts=false; \
+  else \
+    echo "Lockfile not found." && exit 1; \
   fi
 
 FROM base AS builder
@@ -17,9 +25,14 @@ COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
 RUN \
-  if [ -f yarn.lock ]; then yarn run build; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
-  else echo "Lockfile not found." && exit 1; \
+  if [ -f yarn.lock ]; then \
+    yarn run build; \
+  elif [ -f pnpm-lock.yaml ]; then \
+    corepack enable && \
+    corepack prepare pnpm@10.12.1 --activate && \
+    pnpm run build; \
+  else \
+    echo "Lockfile not found." && exit 1; \
   fi
 
 FROM base AS runner
